## Relevante Keywords finden

Anhand manuell extrahierter Zeitungsseiten aus den Jahren 1814-1900 (jeweils erste Juliwoche), die Rezensionen bzw. sonstige Texte mit Literaturthematik enthalten, wird in diesem Notebook versucht, relevante Keywords zu finden, die in zahlreichen Texten mit Literaturthematik und möglichst wenig Texten zu anderen Themen auftreten.

Ziel: Für die automatische Extraktion eine Vorauswahl an Seiten anhand von Keywords auswählen, die dann an die LLMs übergeben werden können und eine sinnvolle Balance aus Precision/Recall gewährleisten.

In [ ]:
import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/rezensionen_for_keyword_extraction.xlsx")


df.columns = df.iloc[0]
df = df.iloc[1:]

df

,ID,pagenumber,day,publication_date,review_text,"category (werbung, gelehrt, rezension, information, notiz)",note,contains_keywords
1,1,4,Sa,06.07.1816,"Handbuch der Sprachwissenschaft,mit besonderer...",werbung,NaN,NaN
2,2,3,So,07.07.1816,"Bei Heinr. Rommerskirchen, Buchhändler dahier,...",werbung,NaN,NaN
3,3,4,So,07.07.1816,nur so piele Exemplare werden auf Postpapter a...,werbung,continues 2,NaN
4,4,3,Do,02.07.1818,Unser Planet oder die Erde in mathematischer u...,werbung,NaN,NaN
5,5,3,Sa,04.07.1818,"DüMont Schauberg in Köln ist zu18e erlangen, P...",werbung,NaN,NaN
...,...,...,...,...,...,...,...,...
496,496,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.dropna(
    how="all",
    subset=df.columns.difference(["ID"])
)
df

,ID,pagenumber,day,publication_date,review_text,"category (werbung, gelehrt, rezension, information, notiz)",note,contains_keywords
1,1,4,Sa,06.07.1816,"Handbuch der Sprachwissenschaft,mit besonderer...",werbung,NaN,NaN
2,2,3,So,07.07.1816,"Bei Heinr. Rommerskirchen, Buchhändler dahier,...",werbung,NaN,NaN
3,3,4,So,07.07.1816,nur so piele Exemplare werden auf Postpapter a...,werbung,continues 2,NaN
4,4,3,Do,02.07.1818,Unser Planet oder die Erde in mathematischer u...,werbung,NaN,NaN
5,5,3,Sa,04.07.1818,"DüMont Schauberg in Köln ist zu18e erlangen, P...",werbung,NaN,NaN
...,...,...,...,...,...,...,...,...
471,471,9,Mi,05.07.1899,[Victor Cherbuliez.] Daß der am 2. d. M. erfol...,"bericht, rezension",interessanter Fall: negative Bewertungen in To...,NaN
472,472,6,Do,06.07.1899,Erfahrungen und Ratschläge eines alten Arztes....,rezension (gebrauch),NaN,NaN
473,473,9,So,1900-07-01 00:00:00,Literatur.Rechtswissenschaft.* Vergleichende D...,rezension (gebrauch),NaN,NaN
474,474,10,So,1900-07-01 00:00:00,die Ausführungs=Verordnungen und=Verfügungen. ...,rezension (gebrauch),continues 473,NaN
475,475,1,Fr,1900-07-06 00:00:00,[Eine prächtige Blütenlese neuester sprachlich...,rezension,NaN,NaN

### Funktion: Ist ein Keyword im übergebenen Text enthalten?

In [ ]:
def extract_keywords(text, keywords):
    if pd.isna(text):
        return []

    text_norm = text.lower()
    return [kw for kw in keywords if kw.lower() in text_norm]

In [ ]:
keywords = ["Kapitel", "Capitel", "Literatur", "Litteratur", "literarisch", "litterarisch","Gedicht", "Roman", "Neuerscheinung", "Dichter", "Schriftsteller", "Schriftst.", "Rezensent", "Recension", "Recensent", "erschienen", "erscheinen", "Werk", "Schrift", "Rezension", "Buch", "Autor", "Verfasser", "verfasst", "herausgegeben", "Herausgeber", "Uebersetzung", "Übersetzung", "übersetzt", "uebersetzt", "lesen", "lesenswert", "Leser", "Büchlein", "Buechlein", "Schrift", "Werk", "Poesie", "Poet"]

In [ ]:
df["contains_keywords"] = df["review_text"].apply(
    extract_keywords,
    keywords=keywords
)

In [ ]:
df.to_excel("july_df_with_keywords.xlsx", index=False)

In [ ]:
exploded = df.explode("contains_keywords")

In [ ]:
exploded = exploded.dropna(subset=["contains_keywords"])

In [ ]:
total_counts = (
    exploded
    .groupby("contains_keywords")
    .size()
    .rename("count_total")
)

rezension_mask = exploded["category (werbung, gelehrt, rezension, information, notiz)"].str.contains(
    "rezension",
    case=False,
    na=False
)

rezension_counts = (
    exploded[rezension_mask]
    .groupby("contains_keywords")
    .size()
    .rename("count_rezension")
)

In [ ]:
result = (
    pd.concat([total_counts, rezension_counts], axis=1)
    .fillna(0)
    .astype(int)
    .reset_index()
    .rename(columns={"contains_keywords": "keyword"})
)

In [ ]:
print(result)

           keyword  count_total  count_rezension
0            Autor           31               25
1             Buch          332              150
2         Büchlein           33               19
3          Capitel           12                7
4          Dichter           76               56
5          Gedicht           66               37
6      Herausgeber           29               18
7          Kapitel            2                1
8            Leser           69               55
9        Literatur          119               94
10      Litteratur           14                4
11          Poesie           24               19
12            Poet           37               27
13       Recension            5                1
14       Rezension            1                0
15           Roman           80               55
16         Schrift          446              234
17  Schriftsteller           53               38
18    Uebersetzung           50               27
19       Verfasser          194              133
20            Werk          528              286
21      erscheinen          101               54
22      erschienen          263              107
23   herausgegeben          109               51
24           lesen           78               52
25      lesenswert           11               11
26     literarisch           53               37
27    litterarisch            3                0
28      uebersetzt            6                2
29        verfasst            2                1
30       übersetzt           36               16

In [ ]:
result.to_excel("keyword_counts.xlsx", index=False)

### Der nächste Schritt

Wir wollen ein Dataframe mit allen Artikeln aus den jeweiligen Jahren im entsprechenden Zeitraum erstellen.

In [ ]:
!pip install ddbapi
from ddbapi import zp_pages, list_column, filter

Collecting ddbapi
  Downloading ddbapi-0.1.2.tar.gz (5.2 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from ddbapi) (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from ddbapi) (2.2.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from ddbapi) (2.5.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->ddbapi) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->ddbapi) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->ddbapi) (2026.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->ddbapi) (1.17.0)
Building wheels for collected packages: ddbapi
  Building wheel for ddbapi (setup.py) ... done
  Created wheel for ddbapi: filename=ddbapi-0.1.2-py3-none-any.whl size=5381 sha256=ad4eb6024f7d9918fceb18a0c7dcd5fa394dcd4e393a119444739e8ef6fcde24
  Stored in directory: /root/.cache/pip/wheels/b9/fa/90/7b6f9ccac9679cba8b348ae6ba003902e1fdc4d44d4b613c38
Successfully built ddbapi
Installing collected packages: ddbapi
Successfully installed ddbapi-0.1.2

In [ ]:
import pandas as pd

dfs = []

for year in range(1814, 1901):  # inklusive 1900
    date_range = f'[{year}-07-01T12:00:00Z TO {year}-07-07T12:00:00Z]'
    print(f"Fetching {year}...")

    df_year = zp_pages(
        publication_date=date_range,
        paper_title='Kölnische Zeitung'
        # kein plainpagefulltext-Filter, somit alle Seiten
    )

    dfs.append(df_year)

# alle Jahre zusammenführen
huge_df = pd.concat(dfs, ignore_index=True)

Fetching 1814...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1814-07-01T12%3A00%3A00Z%5C+TO%5C+1814-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 16 items.
Fetching 1815...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1815-07-01T12%3A00%3A00Z%5C+TO%5C+1815-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 26 items.
Fetching 1816...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1816-07-01T12%3A00%3A00Z%5C+TO%5C+1816-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 20 items.
Fetching 1817...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1817-07-01T12%3A00%3A00Z%5C+TO%5C+1817-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 16 items.
Fetching 1818...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1818-07-01T12%3A00%3A00Z%5C+TO%5C+1818-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 16 items.
Fetching 1819...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1819-07-01T12%3A00%3A00Z%5C+TO%5C+1819-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 20 items.
Fetching 1820...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1820-07-01T12%3A00%3A00Z%5C+TO%5C+1820-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 20 items.
Fetching 1821...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1821-07-01T12%3A00%3A00Z%5C+TO%5C+1821-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 18 items.
Fetching 1822...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1822-07-01T12%3A00%3A00Z%5C+TO%5C+1822-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 16 items.
Fetching 1823...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1823-07-01T12%3A00%3A00Z%5C+TO%5C+1823-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 24 items.
Fetching 1824...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1824-07-01T12%3A00%3A00Z%5C+TO%5C+1824-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 22 items.
Fetching 1825...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1825-07-01T12%3A00%3A00Z%5C+TO%5C+1825-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 22 items.
Fetching 1826...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1826-07-01T12%3A00%3A00Z%5C+TO%5C+1826-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 26 items.
Fetching 1827...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1827-07-01T12%3A00%3A00Z%5C+TO%5C+1827-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 28 items.
Fetching 1828...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1828-07-01T12%3A00%3A00Z%5C+TO%5C+1828-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 28 items.
Fetching 1829...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1829-07-01T12%3A00%3A00Z%5C+TO%5C+1829-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 30 items.
Fetching 1830...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1830-07-01T12%3A00%3A00Z%5C+TO%5C+1830-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 34 items.
Fetching 1831...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1831-07-01T12%3A00%3A00Z%5C+TO%5C+1831-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 36 items.
Fetching 1832...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1832-07-01T12%3A00%3A00Z%5C+TO%5C+1832-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 38 items.
Fetching 1833...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1833-07-01T12%3A00%3A00Z%5C+TO%5C+1833-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 38 items.
Fetching 1834...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1834-07-01T12%3A00%3A00Z%5C+TO%5C+1834-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 38 items.
Fetching 1835...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1835-07-01T12%3A00%3A00Z%5C+TO%5C+1835-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 38 items.
Fetching 1836...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1836-07-01T12%3A00%3A00Z%5C+TO%5C+1836-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 36 items.
Fetching 1837...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1837-07-01T12%3A00%3A00Z%5C+TO%5C+1837-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 36 items.
Fetching 1838...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1838-07-01T12%3A00%3A00Z%5C+TO%5C+1838-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 30 items.
Fetching 1839...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1839-07-01T12%3A00%3A00Z%5C+TO%5C+1839-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 38 items.
Fetching 1840...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1840-07-01T12%3A00%3A00Z%5C+TO%5C+1840-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 38 items.
Fetching 1841...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1841-07-01T12%3A00%3A00Z%5C+TO%5C+1841-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 38 items.
Fetching 1842...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1842-07-01T12%3A00%3A00Z%5C+TO%5C+1842-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 52 items.
Fetching 1843...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1843-07-01T12%3A00%3A00Z%5C+TO%5C+1843-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 60 items.
Fetching 1844...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1844-07-01T12%3A00%3A00Z%5C+TO%5C+1844-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 52 items.
Fetching 1845...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1845-07-01T12%3A00%3A00Z%5C+TO%5C+1845-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 42 items.
Fetching 1846...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1846-07-01T12%3A00%3A00Z%5C+TO%5C+1846-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 50 items.
Fetching 1847...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1847-07-01T12%3A00%3A00Z%5C+TO%5C+1847-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 62 items.
Fetching 1848...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1848-07-01T12%3A00%3A00Z%5C+TO%5C+1848-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 52 items.
Fetching 1849...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1849-07-01T12%3A00%3A00Z%5C+TO%5C+1849-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 56 items.
Fetching 1850...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1850-07-01T12%3A00%3A00Z%5C+TO%5C+1850-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 56 items.
Fetching 1851...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1851-07-01T12%3A00%3A00Z%5C+TO%5C+1851-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 60 items.
Fetching 1852...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1852-07-01T12%3A00%3A00Z%5C+TO%5C+1852-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 44 items.
Fetching 1853...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1853-07-01T12%3A00%3A00Z%5C+TO%5C+1853-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 30 items.
Fetching 1854...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1854-07-01T12%3A00%3A00Z%5C+TO%5C+1854-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 46 items.
Fetching 1855...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1855-07-01T12%3A00%3A00Z%5C+TO%5C+1855-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 52 items.
Fetching 1856...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1856-07-01T12%3A00%3A00Z%5C+TO%5C+1856-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 50 items.
Fetching 1857...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1857-07-01T12%3A00%3A00Z%5C+TO%5C+1857-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 56 items.
Fetching 1858...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1858-07-01T12%3A00%3A00Z%5C+TO%5C+1858-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 42 items.
Fetching 1859...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1859-07-01T12%3A00%3A00Z%5C+TO%5C+1859-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 40 items.
Fetching 1860...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1860-07-01T12%3A00%3A00Z%5C+TO%5C+1860-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 48 items.
Fetching 1861...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1861-07-01T12%3A00%3A00Z%5C+TO%5C+1861-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 46 items.
Fetching 1862...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1862-07-01T12%3A00%3A00Z%5C+TO%5C+1862-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 50 items.
Fetching 1863...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1863-07-01T12%3A00%3A00Z%5C+TO%5C+1863-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 46 items.
Fetching 1864...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1864-07-01T12%3A00%3A00Z%5C+TO%5C+1864-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 50 items.
Fetching 1865...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1865-07-01T12%3A00%3A00Z%5C+TO%5C+1865-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 50 items.
Fetching 1866...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1866-07-01T12%3A00%3A00Z%5C+TO%5C+1866-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 46 items.
Fetching 1867...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1867-07-01T12%3A00%3A00Z%5C+TO%5C+1867-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 46 items.
Fetching 1868...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1868-07-01T12%3A00%3A00Z%5C+TO%5C+1868-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 44 items.
Fetching 1869...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1869-07-01T12%3A00%3A00Z%5C+TO%5C+1869-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 44 items.
Fetching 1870...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1870-07-01T12%3A00%3A00Z%5C+TO%5C+1870-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 58 items.
Fetching 1871...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1871-07-01T12%3A00%3A00Z%5C+TO%5C+1871-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 58 items.
Fetching 1872...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1872-07-01T12%3A00%3A00Z%5C+TO%5C+1872-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 56 items.
Fetching 1873...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1873-07-01T12%3A00%3A00Z%5C+TO%5C+1873-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 66 items.
Fetching 1874...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1874-07-01T12%3A00%3A00Z%5C+TO%5C+1874-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 70 items.
Fetching 1875...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1875-07-01T12%3A00%3A00Z%5C+TO%5C+1875-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 64 items.
Fetching 1876...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1876-07-01T12%3A00%3A00Z%5C+TO%5C+1876-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 64 items.
Fetching 1877...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1877-07-01T12%3A00%3A00Z%5C+TO%5C+1877-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 54 items.
Fetching 1878...
https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1878-07-01T12%3A00%3A00Z%5C+TO%5C+1878-07-07T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Got 52 items.
Fetching 1879...

In [ ]:
huge_df["contains_keywords"] = huge_df["plainpagefulltext"].apply(
    extract_keywords,
    keywords=keywords
)

In [ ]:
huge_df.to_csv("july_df_with_keywords.csv")

In [ ]:
exploded = huge_df.explode("contains_keywords")
exploded = exploded.dropna(subset=["contains_keywords"])

In [ ]:
all_pages_counts = exploded.groupby("contains_keywords").size().rename("all_pages")

In [ ]:
result = result.merge(
    all_pages_counts.rename("all_pages"),
    how="left",
    left_on="keyword",
    right_index=True
)

# fehlende Keywords = 0
result["all_pages"] = result["all_pages"].fillna(0).astype(int)

In [ ]:
print(result)

           keyword  count_total  count_rezension  all_pages
0            Autor           31               25        697
1             Buch          332              150       3253
2         Büchlein           33               19         63
3          Capitel           12                7        235
4          Dichter           76               56        437
5          Gedicht           66               37        266
6      Herausgeber           29               18        186
7          Kapitel            2                1         22
8            Leser           69               55        539
9        Literatur          119               94        439
10      Litteratur           14                4         39
11          Poesie           24               19        103
12            Poet           37               27        172
13       Recension            5                1         15
14       Rezension            1                0          2
15           Roman           80               55        777
16         Schrift          446              234       6546
17  Schriftsteller           53               38        296
18    Uebersetzung           50               27        174
19       Verfasser          194              133        672
20            Werk          528              286       7152
21      erscheinen          101               54       1546
22      erschienen          263              107       1501
23   herausgegeben          109               51        401
24           lesen           78               52       1132
25      lesenswert           11               11         16
26     literarisch           53               37        221
27    litterarisch            3                0         21
28      uebersetzt            6                2          8
29        verfasst            2                1         14
30       übersetzt           36               16        117

In [ ]:
# 1️⃣ Spalten umbenennen
result = result.rename(columns={
    "count_total": "count_literature_themed",
    "count_rezension": "count_review"
})

# 2️⃣ Spaltenreihenfolge anpassen
result = result[["keyword", "all_pages", "count_literature_themed", "count_review"]]

# 3️⃣ Optional: anzeigen
print(result.head())

    keyword  all_pages  count_literature_themed  count_review
0     Autor        697                       31            25
1      Buch       3253                      332           150
2  Büchlein         63                       33            19
3   Capitel        235                       12             7
4   Dichter        437                       76            56

In [ ]:
# 1️⃣ all_pages umbenennen
result = result.rename(columns={"all_pages": "count_all_pages"})

# 2️⃣ Prozentwerte als Kommazahlen (0 bis 1)
result["relevant_literature_themed"] = result["count_literature_themed"] / result["count_all_pages"]
result["relevant_review"] = result["count_review"] / result["count_all_pages"]

# 3️⃣ Spaltenreihenfolge
result = result[[
    "keyword",
    "count_all_pages",
    "count_literature_themed",
    "count_review",
    "relevant_literature_themed",
    "relevant_review"
]]

# 4️⃣ Optional: anzeigen
print(result.head())

    keyword  count_all_pages  count_literature_themed  count_review  \
0     Autor              697                       31            25
1      Buch             3253                      332           150
2  Büchlein               63                       33            19
3   Capitel              235                       12             7
4   Dichter              437                       76            56

   relevant_literature_themed  relevant_review
0                    0.044476         0.035868
1                    0.102060         0.046111
2                    0.523810         0.301587
3                    0.051064         0.029787
4                    0.173913         0.128146

In [ ]:
# Export als Excel-Datei
result.to_excel("keyword_summary.xlsx", index=False)

In [ ]:
# Filter für Keywords mit mehr als 10% in count_review
keywords_over_10pct = result[result["relevant_review"] > 0.1]["keyword"].tolist()

# Ausgabe
print(keywords_over_10pct)

['Büchlein', 'Dichter', 'Gedicht', 'Leser', 'Literatur', 'Litteratur', 'Poesie', 'Poet', 'Schriftsteller', 'Uebersetzung', 'Verfasser', 'herausgegeben', 'lesenswert', 'literarisch', 'uebersetzt', 'übersetzt']

In [ ]:
rezension_df = df[df["category (werbung, gelehrt, rezension, information, notiz)"].str.contains("rezension", case=False, na=False)].copy()

In [ ]:
def has_top_keyword(keyword_list):
    if not keyword_list:  # leere Liste
        return False
    return any(kw in keywords_over_10pct for kw in keyword_list)

rezension_df["has_top_keyword"] = rezension_df["contains_keywords"].apply(has_top_keyword)

In [ ]:
coverage = rezension_df["has_top_keyword"].mean()
print(f"Abdeckung der Rezensionen durch Top-Keywords: {coverage:.2%}")

Abdeckung der Rezensionen durch Top-Keywords: 90.30%

In [ ]:
top_review_keywords = result.sort_values(by="count_review", ascending=False)

print(top_review_keywords.head(10))

       keyword  count_all_pages  count_literature_themed  count_review  \
20        Werk             7152                      528           286
16     Schrift             6546                      446           234
1         Buch             3253                      332           150
19   Verfasser              672                      194           133
22  erschienen             1501                      263           107
9    Literatur              439                      119            94
4      Dichter              437                       76            56
8        Leser              539                       69            55
15       Roman              777                       80            55
21  erscheinen             1546                      101            54

    relevant_literature_themed  relevant_review
20                    0.073826         0.039989
16                    0.068133         0.035747
1                     0.102060         0.046111
19                    0.288690         0.197917
22                    0.175217         0.071286
9                     0.271071         0.214123
4                     0.173913         0.128146
8                     0.128015         0.102041
15                    0.102960         0.070785
21                    0.065330         0.034929

### Transfer für größeren Zeitraum: Alle Seiten der Kölnischen Zeitung zwischen 1814 bis 1900 extrahieren, danach nach den ausgewählten Keywords filtern.

In [ ]:
!pip install ddbapi
import pandas as pd
from ddbapi import zp_pages, list_column, filter

Requirement already satisfied: ddbapi in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from ddbapi) (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from ddbapi) (2.2.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from ddbapi) (2.5.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->ddbapi) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->ddbapi) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->ddbapi) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->ddbapi) (2026.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->ddbapi) (1.17.0)

In [ ]:
relevant_keywords = ['Büchlein', 'Dichter', 'Gedicht', 'Leser', 'Literatur', 'Litteratur', 'Poesie', 'Poet', 'Schriftsteller', 'Uebersetzung', 'Verfasser', 'herausgegeben', 'lesenswert', 'literarisch', 'uebersetzt', 'übersetzt']

In [ ]:
df_to_be_filtered = zp_pages(
        publication_date='[1814-01-01T12:00:00Z TO 1900-12-31T12:00:00Z]',
        paper_title='Kölnische Zeitung'
        # kein plainpagefulltext-Filter, somit alle Seiten
        )

https://api.deutsche-digitale-bibliothek.de/search/index/newspaper-issues/select?rows=1000&sort=id+ASC&q=type%3Apage+AND+publication_date%3A%22%5B1814-01-01T12%3A00%3A00Z%5C+TO%5C+1900-12-31T12%3A00%3A00Z%5D%22+AND+paper_title%3A%22K%C3%B6lnische%5C+Zeitung%22&cursorMark=%2A
Getting 1000 of 224927
Getting 2000 of 224927
Getting 3000 of 224927
Getting 4000 of 224927
Getting 5000 of 224927
Getting 6000 of 224927
Getting 7000 of 224927
Getting 8000 of 224927
Getting 9000 of 224927
Getting 10000 of 224927
Getting 11000 of 224927
Getting 12000 of 224927
Getting 13000 of 224927
Getting 14000 of 224927
Getting 15000 of 224927
Getting 16000 of 224927
Getting 17000 of 224927
Getting 18000 of 224927
Getting 19000 of 224927
Getting 20000 of 224927
Getting 21000 of 224927
Getting 22000 of 224927
Getting 23000 of 224927
Getting 24000 of 224927
Getting 25000 of 224927
Getting 26000 of 224927
Getting 27000 of 224927
Getting 28000 of 224927
Getting 29000 of 224927
Getting 30000 of 224927
Getting 31000 of 224927
Getting 32000 of 224927
Getting 33000 of 224927
Getting 34000 of 224927
Getting 35000 of 224927
Getting 36000 of 224927
Getting 37000 of 224927
Getting 38000 of 224927
Getting 39000 of 224927
Getting 40000 of 224927
Getting 41000 of 224927
Getting 42000 of 224927
Getting 43000 of 224927
Getting 44000 of 224927
Getting 45000 of 224927
Getting 46000 of 224927
Getting 47000 of 224927
Getting 48000 of 224927
Getting 49000 of 224927
Getting 50000 of 224927
Getting 51000 of 224927
Getting 52000 of 224927
Getting 53000 of 224927
Getting 54000 of 224927
Getting 55000 of 224927
Getting 56000 of 224927
Getting 57000 of 224927
Getting 58000 of 224927
Getting 59000 of 224927
Getting 60000 of 224927
Getting 61000 of 224927
Getting 62000 of 224927
Getting 63000 of 224927
Getting 64000 of 224927
Getting 65000 of 224927
Getting 66000 of 224927
Getting 67000 of 224927
Getting 68000 of 224927
Getting 69000 of 224927
Getting 70000 of 224927
Getting 71000 of 224927
Getting 72000 of 224927
Getting 73000 of 224927
Getting 74000 of 224927
Getting 75000 of 224927
Getting 76000 of 224927
Getting 77000 of 224927
Getting 78000 of 224927
Getting 79000 of 224927
Getting 80000 of 224927
Getting 81000 of 224927
Getting 82000 of 224927
Getting 83000 of 224927
Getting 84000 of 224927
Getting 85000 of 224927
Getting 86000 of 224927
Getting 87000 of 224927
Getting 88000 of 224927
Getting 89000 of 224927
Getting 90000 of 224927
Getting 91000 of 224927
Getting 92000 of 224927
Getting 93000 of 224927
Getting 94000 of 224927
Getting 95000 of 224927
Getting 96000 of 224927
Getting 97000 of 224927
Getting 98000 of 224927
Getting 99000 of 224927
Getting 100000 of 224927
Getting 101000 of 224927
Getting 102000 of 224927
Getting 103000 of 224927
Getting 104000 of 224927
Getting 105000 of 224927
Getting 106000 of 224927
Getting 107000 of 224927
Getting 108000 of 224927
Getting 109000 of 224927
Getting 110000 of 224927
Getting 111000 of 224927
Getting 112000 of 224927
Getting 113000 of 224927
Getting 114000 of 224927
Getting 115000 of 224927
Getting 116000 of 224927
Getting 117000 of 224927
Getting 118000 of 224927
Getting 119000 of 224927
Getting 120000 of 224927
Getting 121000 of 224927
Getting 122000 of 224927
Getting 123000 of 224927
Getting 124000 of 224927
Getting 125000 of 224927
Getting 126000 of 224927
Getting 127000 of 224927
Getting 128000 of 224927
Getting 129000 of 224927
Getting 130000 of 224927
Getting 131000 of 224927
Getting 132000 of 224927
Getting 133000 of 224927
Getting 134000 of 224927
Getting 135000 of 224927
Getting 136000 of 224927
Getting 137000 of 224927
Getting 138000 of 224927
Getting 139000 of 224927
Getting 140000 of 224927
Getting 141000 of 224927
Getting 142000 of 224927
Getting 143000 of 224927
Getting 144000 of 224927
Getting 145000 of 224927
Getting 146000 of 224927
Getting 147000 of 224927
Getting 148000 of 224927
Getting 149000 of 224927
Getting 150000 of 224927
Getting 151000 of 224927
Getting 152000 of 224927
Getting 153000 of 224927
Getting 154000 of 224927
Getting 155000 of 224927
Getting 156000 of 224927
Getting 157000 of 224927
Getting 158000 of 224927
Getting 159000 of 224927
Getting 160000 of 224927
Getting 161000 of 224927
Getting 162000 of 224927
Getting 163000 of 224927
Getting 164000 of 224927
Getting 165000 of 224927
Getting 166000 of 224927
Getting 167000 of 224927
Getting 168000 of 224927
Getting 169000 of 224927
Getting 170000 of 224927
Getting 171000 of 224927
Getting 172000 of 224927
Getting 173000 of 224927
Getting 174000 of 224927
Getting 175000 of 224927
Getting 176000 of 224927
Getting 177000 of 224927
Getting 178000 of 224927
Getting 179000 of 224927
Getting 180000 of 224927
Getting 181000 of 224927
Getting 182000 of 224927
Getting 183000 of 224927
Getting 184000 of 224927
Getting 185000 of 224927
Getting 186000 of 224927
Getting 187000 of 224927
Getting 188000 of 224927
Getting 189000 of 224927
Getting 190000 of 224927
Getting 191000 of 224927
Getting 192000 of 224927
Getting 193000 of 224927
Getting 194000 of 224927
Getting 195000 of 224927
Getting 196000 of 224927
Getting 197000 of 224927
Getting 198000 of 224927
Getting 199000 of 224927
Getting 200000 of 224927
Getting 201000 of 224927
Getting 202000 of 224927
Getting 203000 of 224927
Getting 204000 of 224927
Getting 205000 of 224927
Getting 206000 of 224927
Getting 207000 of 224927
Getting 208000 of 224927
Getting 209000 of 224927
Getting 210000 of 224927
Getting 211000 of 224927
Getting 212000 of 224927
Getting 213000 of 224927
Getting 214000 of 224927
Getting 215000 of 224927
Getting 216000 of 224927
Getting 217000 of 224927
Getting 218000 of 224927
Getting 219000 of 224927
Getting 220000 of 224927
Getting 221000 of 224927
Getting 222000 of 224927
Getting 223000 of 224927
Getting 224000 of 224927
Getting 224927 of 224927
Got 224927 items.

In [ ]:
df_to_be_filtered["contains_keywords"] = df_to_be_filtered["plainpagefulltext"].apply(
    extract_keywords,
    keywords=relevant_keywords
)

In [ ]:
# Kopieren, in dem kopierten df alle Einträge droppen, die keine Keywords enthalten. Beide (keyword_df, df_to_be_filtered)als csv exportieren

In [ ]:
# 1️⃣ Gesamtes DataFrame exportieren
#df_to_be_filtered.to_csv("df_to_be_filtered_all.csv", index=False)

# 2️⃣ Nur Einträge exportieren, die mindestens ein Keyword enthalten
df_to_be_filtered[df_to_be_filtered["contains_keywords"].map(bool)] \
   .to_csv("df_full_keywords.csv", index=False)

In [ ]:
from google.colab import files
files.download("/content/df_full_keywords.csv")